#!/usr/bin/env bash
. "$DOCKER_DEVBOX_SCRIPTS_PATH/.bash.lib.d/50-docker"

run --workdir="$(_docker_workdir "/workdir")" db pg_dump --dbname=postgres://gfi-centre-portail:gfi-centre-portail@db/gfi-centre-portail "$@"
